package com.redhat.switchyard.feedback.service
import org.switchyard.Message
import com.redhat.switchyard.feedback.model.Feedback
global Message message

// Rule that checks whether the entered email has a redhat email domain
// The RHS of the rule will set the priority flag on the Feedback object
rule "FeedbackRules"
    when
        $feedback : Feedback(email matches ".*@redhat.com$");
    then
        System.out.println("Red Hat Email Found. Setting Priority Flag");
        $feedback.setPriority(true);
end
